### ISSUE TITLE
Issue: "Seen By" feature

### ISSUE THREAD

**Issue by jgtaft** [difrad/truman_testdrive#7]
The "seen by" feature from EatSnapLove is visible on TestDrive - this is confusing to some kids and in the case of the likes module is contradicting the number of likes we've assigned the posts. I think it would be best to remove it from all of the lessons.

**Comment by difrad** [comment]
Taking this element out of all lessons

**Comment by jgtaft** [comment]
"Seen By" is still visible on the posts on individual users' profile pages

**Comment by difrad** [comment]
Good catch, now fixed.
